spring:
  #Application Config
  application:
    name: media_service
  threads:
    virtual:
      enabled: true

  #Database Config
  datasource:
    url: jdbc:postgresql://localhost:5432/media_service
    username: postgres
    password: NgocLe*2004
    driver-class-name: org.postgresql.Driver

  #JPA Config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#Server Config
server:
  port: 8082

#Another Service
internal:
  secret: internal_secret

#File System Config
file:
  directoty: