spring:
  #Application Config
  application:
    name: payment_service


#VNPAY Config
vnpay:
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return_url: //
  tmn_code: //
  secret_key: //
  api_url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  version: 2.1.0


#Paypal Config
paypal:
  client-id: -----------------Your Client ID(Keep it secret)-------------------
  client-secret: -------------------------Your Client Secret(Keep it secret)--------------------------
  mode: sandbox #Sandbox for Testing, Live for Production