spring:
  #Application Config
  application:
    name: product_service
  threads:
    virtual:
      enabled: true

  #Database Config
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: postgres
    password: NgocLe*2004
    driver-class-name: org.postgresql.Driver

  #JPA Config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#Server Config
server:
  port: 8084

#Another Service
internal:
  secret: internal_secret

service:
  auth: //
  media: //

